### ISSUE TITLE
workflow doesn't run if .workflow directory doesn't exist

### ISSUE THREAD

**Issue by gabegaster** [deanmalmgren/flo#42]
It's fixed if I `mkdir .workflow` first. 

See:

```
  $ workflow --export
  Traceback (most recent call last):
File "/usr/local/bin/workflow", line 10, in <module>
  execfile(__file__)
File "/DivvyVoronoi/src/workflow/bin/workflow", line 32, in <module>
  available_tasks = get_available_tasks()
File "/DivvyVoronoi/src/workflow/workflow/parser.py", line 94, in get_available_tasks
  task_graph = load_task_graph()
File "/DivvyVoronoi/src/workflow/workflow/parser.py", line 77, in load_task_graph
  task_graph = tasks.TaskGraph(config_path)
File "/DivvyVoronoi/src/workflow/workflow/tasks.py", line 277, in __init__
  self.logger = logger.configure(self)
File "/DivvyVoronoi/src/workflow/workflow/logger.py", line 21, in configure
  file_handler = ColorlessFileHandler(task_graph.abs_log_path, mode='w')
File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 903, in __init__
  StreamHandler.__init__(self, self._open())
File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 926, in _open
  stream = open(self.baseFilename, self.mode)
  IOError: [Errno 2] No such file or directory: '/DivvyVoronoiPublic/.workflow/workflow.log'
```

**Comment by deanmalmgren** [comment]
I think this was resolved by df7369019d8d2275dcd4095c642fa24486943fd1
